/*
 * This file is generated by jOOQ.
 */
package com.gulyaich.boot.jooq.tables.records;


import com.gulyaich.boot.jooq.tables.News;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Таблица студентов
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsRecord extends UpdatableRecordImpl<NewsRecord> implements Record4<Long, String, String, Timestamp> {

    private static final long serialVersionUID = -1385418876;

    /**
     * Setter for <code>PUBLIC.NEWS.NEWS_ID</code>.
     */
    public void setNewsId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.NEWS.NEWS_ID</code>.
     */
    public Long getNewsId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.NEWS.TITLE</code>. Заголовок новости
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.NEWS.TITLE</code>. Заголовок новости
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.NEWS.BODY</code>. Текст новости
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.NEWS.BODY</code>. Текст новости
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.NEWS.DATE</code>. Дата новости
     */
    public void setDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.NEWS.DATE</code>. Дата новости
     */
    public Timestamp getDate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return News.NEWS.NEWS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return News.NEWS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return News.NEWS.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return News.NEWS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getNewsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getNewsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value1(Long value) {
        setNewsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value3(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value4(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord values(Long value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsRecord
     */
    public NewsRecord() {
        super(News.NEWS);
    }

    /**
     * Create a detached, initialised NewsRecord
     */
    public NewsRecord(Long newsId, String title, String body, Timestamp date) {
        super(News.NEWS);

        set(0, newsId);
        set(1, title);
        set(2, body);
        set(3, date);
    }
}
