/*
 * This file is generated by jOOQ.
 */
package com.gulyaich.boot.jooq;


import com.gulyaich.boot.jooq.tables.News;
import com.gulyaich.boot.jooq.tables.Student;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_A = Indexes0.PRIMARY_KEY_A;
    public static final Index IX_STUDENT_LAST_NAME = Indexes0.IX_STUDENT_LAST_NAME;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_A = Internal.createIndex("PRIMARY_KEY_A", News.NEWS, new OrderField[] { News.NEWS.NEWS_ID }, true);
        public static Index IX_STUDENT_LAST_NAME = Internal.createIndex("IX_STUDENT_LAST_NAME", Student.STUDENT, new OrderField[] { Student.STUDENT.LAST_NAME }, false);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", Student.STUDENT, new OrderField[] { Student.STUDENT.STUDENT_ID }, true);
    }
}
