/*
 * This file is generated by jOOQ.
 */
package com.gulyaich.boot.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.HIBERNATE_SEQUENCE</code>
     */
    public static final Sequence<Long> HIBERNATE_SEQUENCE = new SequenceImpl<Long>("HIBERNATE_SEQUENCE", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SEQ_NEWS_ID</code>
     */
    public static final Sequence<Long> SEQ_NEWS_ID = new SequenceImpl<Long>("SEQ_NEWS_ID", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SEQ_STUDENT_ID</code>
     */
    public static final Sequence<Long> SEQ_STUDENT_ID = new SequenceImpl<Long>("SEQ_STUDENT_ID", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
