/*
 * This file is generated by jOOQ.
 */
package com.gulyaich.boot.jooq;


import com.gulyaich.boot.jooq.tables.News;
import com.gulyaich.boot.jooq.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Таблица студентов
     */
    public static final News NEWS = com.gulyaich.boot.jooq.tables.News.NEWS;

    /**
     * Таблица студентов
     */
    public static final Student STUDENT = com.gulyaich.boot.jooq.tables.Student.STUDENT;
}
